kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dogs-reader
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups: ["frens.teq0.com"]
  resources: ["dogs"]
  verbs: ["get", "watch", "list"]