apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dogs.frens.teq0.com
spec:
  group: frens.teq0.com
  versions:
    - name: v1
      served: true
      storage: true
  version: v1
  scope: Cluster
  names:
    plural: dogs
    singular: dog
    kind: Dog
    shortNames:
    - dogue
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          properties:
            name:
              type: string
            isGood:
              type: boolean
            food:
              type: string
